//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizPract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oborudovanie()
        {
            this.Characteristiki_oborudovania = new HashSet<Characteristiki_oborudovania>();
            this.Istoriya_obslugivaniya = new HashSet<Istoriya_obslugivaniya>();
            this.Stoimost = new HashSet<Stoimost>();
            this.Vidannoe_oborudovanie = new HashSet<Vidannoe_oborudovanie>();
        }
    
        public int id_oborud { get; set; }
        public string naimenovanie { get; set; }
        public string type { get; set; }
        public string model { get; set; }
        public int seriin_nom { get; set; }
        public System.DateTime data_priobr { get; set; }
        public string srok_slugb { get; set; }
        public string sostoyanie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Characteristiki_oborudovania> Characteristiki_oborudovania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Istoriya_obslugivaniya> Istoriya_obslugivaniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoimost> Stoimost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vidannoe_oborudovanie> Vidannoe_oborudovanie { get; set; }
    }
}
