//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizPract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoimost
    {
        public int id_stoim { get; set; }
        public int id_oborud { get; set; }
        public int count { get; set; }
        public int cost { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
    }
}
