//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProizPract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vidannoe_oborudovanie
    {
        public int id_vidachi { get; set; }
        public int id_oborud { get; set; }
        public int id_user { get; set; }
        public System.DateTime data_vidachi { get; set; }
        public Nullable<System.DateTime> data_vozvrata { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
